//获取用户所有项目信息
export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
//是否显示对话框
export const OPEN_SELECT_PROJECTS = 'OPEN_SELECT_PROJECTS';
